name: Linux build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fetch submodules
      run: git submodule update --init --recursive

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y ninja-build cmake \
                           libx11-dev libxext-dev libxrandr-dev libxcursor-dev \
                           libxi-dev libxinerama-dev libwayland-dev libxkbcommon-dev \
                           wayland-protocols

    - name: Configure CMake
      run: cmake --fresh -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_USER_BUILD=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel $(nproc)

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: ChonkyStation3 
        path: ./build/ChonkyStation3
